PARAM_MQ_URL = 'MQ_URL'
PARAM_MQ_HOST = 'MQ_HOST'
PARAM_MQ_PORT = 'MQ_PORT'
PARAM_CERT_PATH = 'CERT_PEM'
PARAM_KEY_PATH = 'KEY_PEM'
PARAM_CA_PATH = 'CA_PATH'

ENV_WEB_PORT = 'WEB_PORT'

APP_NAME = 'reception'
WEB_APP_PATH = '/reception'
